### ISSUE TITLE
[Question] Do you have a LICENSE for FileKit?

### ISSUE THREAD

**Issue by trips-app** [eelcokoelewijn/FileKit#1]
I was wondering if FileKit, NetworkKit, and CollectionViewKit are available under the MIT license?

I would like to use at least one of them in an app I am developing, where they will be useful.

Thanks.

--mike

**Comment by eelcokoelewijn** [comment]
Hi Mike,

I'm not planning to add any license for these repo's, they are used in hobby projects and experiments.
Feel free to use what ever you like, but don't expect support or frequent updates.

All the best with your project.

Eelco

**Comment by trips-app** [comment]
Hi Eelco.

Thanks for the reply. Great!

Support isn't needed as I will adapt the code myself. This code will be copyrighted to you,
and I'll include a MIT license for it in my app's Acknowledgements section in Settings. 

I'll close this issue too.

--mike
